server:
  servlet:
    context-path: /achat
  port: 8081

spring:
  application:
    name: Esprit-Achat
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/esprit-achat
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
